services:
  - type: web
    name: place-rec-backend
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn config.wsgi:application --worker-tmp-dir /dev/shm --timeout 60"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: DEBUG
        value: "False"
      - fromGroup: place-rec-secrets
    healthCheckPath: /api/places/ping/
    rootContext: backend
